import { useEffect, useMemo, useState } from "react";
import { Card } from "../../components/Card.jsx";
import { getLocalStreamPcStatusReadOnly } from "../../services/localStatusClient.js";

export function StreamPcStatusPage() {
  const [data, setData] = useState({ readOnly: true, server: null, stream: null, ws: null, errors: [] });
  useEffect(() => { let cancelled = false; getLocalStreamPcStatusReadOnly().then((value) => { if (!cancelled) setData(value); }).catch((err) => { if (!cancelled) setData((current) => ({ ...current, errors: [err?.message || String(err)] })); }); return () => { cancelled = true; }; }, []);
  const view = useMemo(() => normalize(data), [data]);
  return <><section className="page-header module-page-header cgn-card"><p className="cgn-eyebrow">System</p><h1>Stream-PC</h1><p>Lokaler Status aus bestehenden sicheren GET-Routen. Diese Seite liest nur und löst keine Aktionen aus.</p></section><section className="metric-grid"><Metric label="Server" value={view.serverOnline ? "Online" : "Unbekannt"} sub={`Port ${view.port}`} /><Metric label="Module" value={String(view.moduleCount)} sub="geladene lokale Module" /><Metric label="WebSocket" value={`${view.wsClients} Clients`} sub="nur Anzeige" /><Metric label="Stream" value={view.streamLabel} sub={view.streamSub} warn={view.streamWarn} /></section><section className="status-grid"><Card title="Lokaler Node/Express" eyebrow="Server"><Info label="Host" value={view.host} /><Info label="Port" value={view.port} /><Info label="Version" value={view.version} /><Info label="Module" value={view.modules.join(', ') || '—'} /></Card><Card title="Cache" eyebrow="Streamstatus"><Info label="Live" value={view.liveText} /><Info label="Titel" value={view.title} /><Info label="Game" value={view.gameName} /><Info label="Quelle" value={view.source} /><Info label="Geprüft" value={view.lastCheckedAt} /></Card><Card title="Verbindungen" eyebrow="WebSocket"><Info label="Clients" value={String(view.wsClients)} /><Info label="Zeit" value={view.wsTime} /><Info label="Status" value="nur Anzeige" /></Card><Card title="Nicht freigegeben" eyebrow="Sicherheitsgrenze"><ul className="plain-list"><li><span>○</span>keine OBS- oder Overlay-Steuerung</li><li><span>○</span>keine Sound- oder Media-Aktionen</li><li><span>○</span>keine Commands oder Prozessaktionen</li><li><span>○</span>keine Refresh-, Test-, Log-, Session- oder Schreibroute</li></ul></Card></section>{view.errors.length ? <section className="error-note">{view.errors.join(' · ')}</section> : null}</>;
}

function Metric({ label, value, sub, warn = false }) { return <article className="metric-card cgn-card"><span>{label}</span><strong>{value}</strong><small>{sub}</small><div className={`cgn-progress ${warn ? "cgn-progress--warn" : ""}`}><i style={{ width: warn ? "45%" : "86%" }}></i></div></article>; }
function Info({ label, value }) { return <div className="kv-row"><span>{label}</span><strong>{value || '—'}</strong></div>; }
function normalize(data) { const server = data.server || {}; const stream = data.stream || {}; const ws = data.ws || {}; const modules = Array.isArray(server.loadedModules) ? server.loadedModules : []; return { serverOnline: server.ok === true, host: server.host || '—', port: server.port || 8080, version: server.serverVersion || '—', modules, moduleCount: modules.length || '—', wsClients: Number(ws.clients ?? server.wsClients ?? 0), wsTime: ws.isoTs || ws.ts || '—', streamLabel: stream.live ? 'Live' : stream.statusKnown === false ? 'Unbekannt' : 'Offline/Cache', streamSub: stream.stale ? 'Cache veraltet' : 'gecacheter Status', streamWarn: Boolean(stream.stale), liveText: stream.live === true ? 'ja' : stream.live === false ? 'nein' : 'unbekannt', title: stream.title || '—', gameName: stream.gameName || '—', source: stream.source || '—', lastCheckedAt: stream.lastCheckedAt || '—', errors: Array.isArray(data.errors) ? data.errors : [] }; }
