'use strict';

const { ADMIN_NOTE_WRITE_CONFIRMED_SUMMARY } = require('../services/admin-user-admin-note-write-confirmed.service');

function registerRoutesRoutes(app, context) {
  app.get('/api/remote/routes', (req, res) => {
    res.json({
      ok: true,
      service: 'remote-modboard',
      module: 'remote_routes',
      moduleBuild: context.moduleBuild,
      statusApiVersion: 'rdap_admin_note_read_restore39c.v1',
      readOnly: false,
      writeEnabled: false,
      authEnabled: Boolean(context.config && context.config.auth && context.config.auth.authEnabled),
      routes: [
        { method: 'GET', path: '/api/remote/health', description: 'Read-only Healthcheck' },
        { method: 'GET', path: '/api/remote/status', description: 'Service-/Security-/Auth-/RDAP39-Status' },
        { method: 'GET', path: '/api/remote/routes', description: 'Routenuebersicht' },
        { method: 'GET', path: '/api/remote/auth/model', description: 'Read-only Auth-/Rechte-Modell' },
        { method: 'GET', path: '/api/remote/auth/me', description: 'Aktueller Login-/Session-Status' },
        { method: 'POST', path: '/api/remote/auth/me/sync-twitch', description: 'Self-Service: eigenes Twitch-Profil synchronisieren' },
        { method: 'GET', path: '/api/remote/auth/session-status', description: 'Read-only Session-Diagnose' },
        { method: 'GET', path: '/api/remote/auth/permissions/check', description: 'Read-only Permission-Diagnose' },
        { method: 'GET', path: '/api/remote/admin/users/permission-diagnostic', description: 'Read-only Admin-User-Permission-Diagnose; keine User-/Rollen-Writes' },
        { method: 'GET', path: '/api/remote/admin/users/write-foundation-diagnostic', description: 'Read-only Confirm-/Audit-/Locking-Foundation inkl. disabled Confirm-/Audit-/Lock-Helper; schreibt nichts' },
        { method: 'GET', path: '/api/remote/admin/users/mini-write-foundation-diagnostic', description: 'Read-only RDAP11 Mini-Write-Foundation; Permission/Confirm/Audit/Lock/Backup/Rollback vorbereitet, Writes bleiben blockiert' },
        { method: 'GET', path: '/api/remote/admin/users/admin-note-diagnostic', description: 'Read-only Admin-Notiz-Tabellen-Diagnose; keine Migration, keine Notiz-Writes' },
        { method: 'GET', path: '/api/remote/admin/users/admin-notes/read', description: 'RDAP39C wiederhergestellte echte Admin-Notiz-Read-Route mit Session, DashboardAccess und admin.users.note.read; schreibt nichts' },
        { method: 'GET', path: '/api/remote/admin/users/admin-notes/write-plan', description: 'RDAP38 Admin-Notiz Write-Plan; read-only' },
        { method: 'POST', path: '/api/remote/admin/users/admin-notes/create', description: 'RDAP39 kontrollierter Admin-Notiz Create-Backend-Write mit Permission/Confirm/Audit/Lock/Readback; keine UI-Schreibbuttons' },
        { method: 'POST', path: '/api/remote/admin/users/admin-notes/update', description: 'RDAP31 Admin-Notiz Update-Validierung; bleibt read-only, schreibt nichts' },
        { method: 'POST', path: '/api/remote/admin/users/admin-notes/deactivate', description: 'RDAP31 Admin-Notiz Deactivate-Validierung; bleibt read-only, schreibt nichts' },
        { method: 'GET', path: '/api/remote/auth/login/plan', description: 'Read-only Plan fuer zentrale Login-Schicht' },
        { method: 'GET', path: '/api/remote/auth/login/start', description: 'Neutraler Login-Einstieg; aktuell Fallback auf Twitch, spaeter zentrale Auth' },
        { method: 'GET', path: '/api/remote/auth/twitch/start', description: 'Gated Twitch OAuth Start' },
        { method: 'GET', path: '/api/remote/auth/twitch/callback', description: 'Gated Twitch OAuth Callback' },
        { method: 'POST', path: '/api/remote/auth/logout', description: 'Gated Logout nur fuer aktuelle Auth-Session' },
        { method: 'GET', path: '/api/remote/lock-audit/status', description: 'Read-only Lock-/Audit-Diagnose' },
        { method: 'GET', path: '/api/remote/lock-audit/schema-adapter/status', description: 'Read-only Schema-Adapter-Diagnose' },
        { method: 'GET', path: '/api/remote/admin/audit-lock/schema-status', description: 'RDAP33 read-only Audit-/Lock-Schema und Runtime-Status; keine Writes' },
        { method: 'GET', path: '/api/remote/lock-audit/schema-status', description: 'Alias fuer RDAP33 read-only Audit-/Lock-Schema und Runtime-Status' },
        { method: 'GET', path: '/api/remote/admin/audit/test-insert/status', description: 'RDAP36 Audit-Testinsert-Status; schreibt nichts' },
        { method: 'POST', path: '/api/remote/admin/audit/test-insert', description: 'RDAP36 lokaler Audit-Testinsert mit Body-confirmWrite und testOnly; keine produktive Admin-Aktion' },
        { method: 'GET', path: '/api/remote/admin/locks/test/status', description: 'RDAP37 Lock-Test-Status; schreibt nichts' },
        { method: 'POST', path: '/api/remote/admin/locks/test-cycle', description: 'RDAP37 lokaler Lock-Test mit Body-confirmWrite und testOnly; keine produktive Admin-Aktion' },
        { method: 'GET', path: '/', description: 'Remote-Modboard UI' },
        { method: 'GET', path: '/remote', description: 'Remote-Modboard UI Alias' },
        { method: 'GET', path: '/modboard', description: 'Remote-Modboard UI Alias' }
      ],
      adminNoteReadRestored: {
        prepared: true,
        route: '/api/remote/admin/users/admin-notes/read',
        method: 'GET',
        statusApiVersion: 'rdap_admin_users27.v1',
        routeRestoreBuild: 'RDAP39C_ADMIN_NOTE_READ_ROUTE_RESTORE_OR_SYNC',
        serviceBuild: 'RDAP_ADMIN_USERS27_ADMIN_NOTE_REAL_READ_ROUTE_AUTHED',
        tableName: 'dashboard_user_admin_notes',
        permissionRequired: 'admin.users.note.read',
        writePermissionObservedOnly: 'admin.users.note.write',
        readOnly: true,
        writeEnabled: false,
        databaseWriteEnabled: false,
        productiveWritesEnabled: false,
        uiWriteButtonsEnabled: false,
        communityPagesMayReadAdminNotes: false,
        returnsNoteTextForAuthorizedAdmins: true,
        routeRemainsRestricted: true
      },
      adminNoteWritePlan: {
        prepared: true,
        route: '/api/remote/admin/users/admin-notes/write-plan',
        method: 'GET',
        statusApiVersion: 'rdap_admin_note_write38.v1',
        tableName: 'dashboard_user_admin_notes',
        permissionRequired: 'admin.users.note.write',
        confirmWriteRequired: true,
        bodyConfirmOnly: true,
        auditRequired: true,
        lockRequired: true,
        backupRequiredBeforeProductiveWrite: true,
        readBackRequired: true,
        writeEnabled: false,
        databaseWriteEnabled: false,
        productiveWritesEnabled: false,
        adminNoteWritesEnabled: false,
        uiWriteButtonsEnabled: false,
        physicalDeleteEnabled: false,
        routeRemainsReadOnly: true
      },
      adminNoteWriteConfirmed: ADMIN_NOTE_WRITE_CONFIRMED_SUMMARY,
      adminUsersAdminNoteWriteDisabled: {
        prepared: true,
        routes: [
          '/api/remote/admin/users/admin-notes/update',
          '/api/remote/admin/users/admin-notes/deactivate'
        ],
        tableName: 'dashboard_user_admin_notes',
        permissionRequired: 'admin.users.note.write',
        confirmWriteRequired: true,
        validatatesInput: true,
        readOnly: true,
        writeEnabled: false,
        databaseWriteEnabled: false,
        productiveWritesEnabled: false,
        uiWriteButtonsEnabled: false,
        updatesNote: false,
        deactivatesNote: false,
        physicalDeleteEnabled: false,
        routeRemainsReadOnly: true
      },
      adminAuditLockSchemaStatusReadonly: {
        prepared: true,
        route: '/api/remote/admin/audit-lock/schema-status',
        aliasRoute: '/api/remote/lock-audit/schema-status',
        statusApiVersion: 'rdap_audit36.v1',
        tables: ['dashboard_audit_log', 'dashboard_locks'],
        readOnly: true,
        writeEnabled: false,
        databaseWriteEnabled: false,
        productiveWritesEnabled: false,
        writesStillBlocked: true,
        migrationEnabled: false,
        returnsRowCounts: true,
        returnsSafePreviewRows: true,
        secretsLogged: false,
        auditInsertEnabled: false,
        lockAcquireEnabled: false,
        lockHeartbeatEnabled: false,
        lockReleaseEnabled: false,
        lockForceTakeoverEnabled: false,
        uiWriteButtonsEnabled: false,
        routeRemainsReadOnly: true
      },
      adminAuditTestInsert: {
        prepared: true,
        statusRoute: '/api/remote/admin/audit/test-insert/status',
        route: '/api/remote/admin/audit/test-insert',
        method: 'POST',
        statusApiVersion: 'rdap_audit36.v1',
        tableName: 'dashboard_audit_log',
        localOnly: true,
        confirmWriteRequired: true,
        bodyConfirmOnly: true,
        testOnlyRequired: true,
        auditTestInsertEnabled: true,
        productiveWritesEnabled: false,
        writesStillBlockedForProductiveActions: true,
        adminNoteWritesEnabled: false,
        lockWritesEnabled: false,
        uiWriteButtonsEnabled: false,
        secretsLogged: false,
        routeRemainsRestricted: true
      },
      adminLockTest: {
        prepared: true,
        statusRoute: '/api/remote/admin/locks/test/status',
        route: '/api/remote/admin/locks/test-cycle',
        method: 'POST',
        statusApiVersion: 'rdap_lock37.v1',
        tableName: 'dashboard_locks',
        localOnly: true,
        confirmWriteRequired: true,
        bodyConfirmOnly: true,
        testOnlyRequired: true,
        lockTestCycleEnabled: true,
        productiveWritesEnabled: false,
        writesStillBlockedForProductiveActions: true,
        adminNoteWritesEnabled: false,
        auditProductiveWritesEnabled: false,
        uiWriteButtonsEnabled: false,
        secretsLogged: false,
        physicalDeleteEnabled: false,
        routeRemainsRestricted: true
      },
      adminUsersMiniWriteFoundation: {
        prepared: true,
        route: '/api/remote/admin/users/mini-write-foundation-diagnostic',
        permissionPrepared: true,
        confirmWritePrepared: true,
        auditPrepared: true,
        lockPrepared: true,
        backupRollbackPrepared: true,
        writeEnabled: false,
        productiveWritesEnabled: false,
        writesStillBlocked: true,
        uiWriteButtonsEnabled: false,
        routeRemainsReadOnly: true
      },
      localLanMode: {
        planned: true,
        implemented: false,
        twitchLoginPlanned: true,
        todoParkedUntilWebDashboardStable: true
      },
      safety: context.safety
    });
  });
}

module.exports = { registerRoutesRoutes };
