'use strict';

function registerRoutesRoutes(app, context) {
  app.get('/api/remote/routes', (req, res) => {
    res.json({
      ok: true,
      service: 'remote-modboard',
      module: 'remote_routes',
      moduleBuild: context.moduleBuild,
      statusApiVersion: 'rdap_lock37.v1',
      readOnly: true,
      writeEnabled: false,
      authEnabled: Boolean(context.config && context.config.auth && context.config.auth.authEnabled),
      routes: [
        { method: 'GET', path: '/api/remote/health', description: 'Read-only Healthcheck' },
        { method: 'GET', path: '/api/remote/status', description: 'Read-only Service-/Security-/Auth-Status' },
        { method: 'GET', path: '/api/remote/routes', description: 'Read-only Routenuebersicht' },
        { method: 'GET', path: '/api/remote/auth/model', description: 'Read-only Auth-/Rechte-Modell' },
        { method: 'GET', path: '/api/remote/auth/me', description: 'Aktueller Login-/Session-Status' },
        { method: 'POST', path: '/api/remote/auth/me/sync-twitch', description: 'Self-Service: eigenes Twitch-Profil synchronisieren' },
        { method: 'GET', path: '/api/remote/auth/session-status', description: 'Read-only Session-Diagnose' },
        { method: 'GET', path: '/api/remote/auth/permissions/check', description: 'Read-only Permission-Diagnose' },
        { method: 'GET', path: '/api/remote/admin/users/permission-diagnostic', description: 'Read-only Admin-User-Permission-Diagnose; keine User-/Rollen-Writes' },
        { method: 'GET', path: '/api/remote/admin/users/write-foundation-diagnostic', description: 'Read-only Confirm-/Audit-/Locking-Foundation inkl. disabled Confirm-/Audit-/Lock-Helper; schreibt nichts' },
        { method: 'GET', path: '/api/remote/admin/users/mini-write-foundation-diagnostic', description: 'Read-only RDAP11 Mini-Write-Foundation; Permission/Confirm/Audit/Lock/Backup/Rollback vorbereitet, Writes bleiben blockiert' },
        { method: 'GET', path: '/api/remote/admin/users/admin-note-diagnostic', description: 'Read-only RDAP14 Admin-Notiz-Tabellen-Diagnose; keine Migration, keine Notiz-Writes' },
        { method: 'POST', path: '/api/remote/admin/users/admin-notes/create', description: 'RDAP31 Admin-Notiz Create-Validierung; bleibt read-only, schreibt nichts' },
        { method: 'POST', path: '/api/remote/admin/users/admin-notes/update', description: 'RDAP31 Admin-Notiz Update-Validierung; bleibt read-only, schreibt nichts' },
        { method: 'POST', path: '/api/remote/admin/users/admin-notes/deactivate', description: 'RDAP31 Admin-Notiz Deactivate-Validierung; bleibt read-only, schreibt nichts' },
        { method: 'GET', path: '/api/remote/auth/login/plan', description: 'Read-only Plan fuer zentrale Login-Schicht' },
        { method: 'GET', path: '/api/remote/auth/login/start', description: 'Neutraler Login-Einstieg; aktuell Fallback auf Twitch, spaeter zentrale Auth' },
        { method: 'GET', path: '/api/remote/auth/twitch/start', description: 'Gated Twitch OAuth Start' },
        { method: 'GET', path: '/api/remote/auth/twitch/callback', description: 'Gated Twitch OAuth Callback' },
        { method: 'POST', path: '/api/remote/auth/logout', description: 'Gated Logout nur fuer aktuelle Auth-Session' },
        { method: 'GET', path: '/api/remote/lock-audit/status', description: 'Read-only Lock-/Audit-Diagnose' },
        { method: 'GET', path: '/api/remote/lock-audit/schema-adapter/status', description: 'Read-only Schema-Adapter-Diagnose' },
        { method: 'GET', path: '/api/remote/admin/audit-lock/schema-status', description: 'RDAP33 read-only Audit-/Lock-Schema und Runtime-Status; keine Writes' },
        { method: 'GET', path: '/api/remote/lock-audit/schema-status', description: 'Alias fuer RDAP33 read-only Audit-/Lock-Schema und Runtime-Status' },
        { method: 'GET', path: '/api/remote/admin/audit/test-insert/status', description: 'RDAP36 Audit-Testinsert-Status; schreibt nichts' },
        { method: 'POST', path: '/api/remote/admin/audit/test-insert', description: 'RDAP36 lokaler Audit-Testinsert mit Body-confirmWrite und testOnly; keine produktive Admin-Aktion' },
        { method: 'GET', path: '/api/remote/admin/locks/test/status', description: 'RDAP37 Lock-Teststatus; schreibt nichts' },
        { method: 'POST', path: '/api/remote/admin/locks/test-cycle', description: 'RDAP37 lokaler Lock-Test Acquire/Heartbeat/Release mit Body-confirmWrite und testOnly; keine produktive Admin-Aktion' },
        { method: 'GET', path: '/', description: 'Remote-Modboard UI' },
        { method: 'GET', path: '/remote', description: 'Remote-Modboard UI Alias' },
        { method: 'GET', path: '/modboard', description: 'Remote-Modboard UI Alias' }
      ],
      adminUsersWriteFoundation: {
        confirmWriteHelperPrepared: true,
        auditHelperPrepared: true,
        lockHelperPrepared: true,
        lockWriteEnabled: false,
        productiveWritesEnabled: false,
        writesStillBlocked: true,
        routeRemainsReadOnly: true
      },
      adminUserAdminNoteDiagnostic: {
        prepared: true,
        route: '/api/remote/admin/users/admin-note-diagnostic',
        tableName: 'dashboard_user_admin_notes',
        readOnly: true,
        writeEnabled: false,
        productiveWritesEnabled: false,
        writesStillBlocked: true,
        migrationEnabled: false,
        routeRemainsReadOnly: true,
        uiWriteButtonsEnabled: false,
        routeListKeySynced: true,
        aliasOf: 'adminUsersAdminNoteDiagnostic'
      },
      adminUsersAdminNoteDiagnostic: {
        prepared: true,
        route: '/api/remote/admin/users/admin-note-diagnostic',
        tableName: 'dashboard_user_admin_notes',
        readOnly: true,
        writeEnabled: false,
        productiveWritesEnabled: false,
        writesStillBlocked: true,
        migrationEnabled: false,
        routeRemainsReadOnly: true,
        uiWriteButtonsEnabled: false,
        routeListKeySynced: true
      },
      adminUsersAdminNoteWriteDisabled: {
        prepared: true,
        routes: [
          '/api/remote/admin/users/admin-notes/create',
          '/api/remote/admin/users/admin-notes/update',
          '/api/remote/admin/users/admin-notes/deactivate'
        ],
        tableName: 'dashboard_user_admin_notes',
        permissionRequired: 'admin.users.note.write',
        confirmWriteRequired: true,
        validatesInput: true,
        validatesSession: true,
        validatesPermissions: true,
        validatesSchemaReadOnly: true,
        validatesTargetUserReadOnly: true,
        auditDraftPrepared: true,
        lockDraftPrepared: true,
        lockWriteEnabled: false,
        auditWriteEnabled: false,
        readOnly: true,
        writeEnabled: false,
        databaseWriteEnabled: false,
        productiveWritesEnabled: false,
        writesStillBlocked: true,
        uiWriteButtonsEnabled: false,
        createsNote: false,
        updatesNote: false,
        deactivatesNote: false,
        deletesNote: false,
        physicalDeleteEnabled: false,
        routeRemainsReadOnly: true
      },
      adminAuditLockSchemaStatusReadonly: {
        prepared: true,
        route: '/api/remote/admin/audit-lock/schema-status',
        aliasRoute: '/api/remote/lock-audit/schema-status',
        statusApiVersion: 'rdap_lock37.v1',
        tables: ['dashboard_audit_log', 'dashboard_locks'],
        readOnly: true,
        writeEnabled: false,
        databaseWriteEnabled: false,
        productiveWritesEnabled: false,
        writesStillBlocked: true,
        migrationEnabled: false,
        returnsRowCounts: true,
        returnsSafePreviewRows: true,
        secretsLogged: false,
        auditInsertEnabled: false,
        lockAcquireEnabled: false,
        lockHeartbeatEnabled: false,
        lockReleaseEnabled: false,
        lockForceTakeoverEnabled: false,
        uiWriteButtonsEnabled: false,
        routeRemainsReadOnly: true
      },
      adminAuditTestInsert: {
        prepared: true,
        statusRoute: '/api/remote/admin/audit/test-insert/status',
        route: '/api/remote/admin/audit/test-insert',
        method: 'POST',
        statusApiVersion: 'rdap_audit36.v1',
        tableName: 'dashboard_audit_log',
        localOnly: true,
        confirmWriteRequired: true,
        bodyConfirmOnly: true,
        testOnlyRequired: true,
        auditTestInsertEnabled: true,
        productiveWritesEnabled: false,
        writesStillBlockedForProductiveActions: true,
        adminNoteWritesEnabled: false,
        lockWritesEnabled: false,
        uiWriteButtonsEnabled: false,
        secretsLogged: false,
        routeRemainsRestricted: true
      },
      adminLockTest: {
        prepared: true,
        statusRoute: '/api/remote/admin/locks/test/status',
        route: '/api/remote/admin/locks/test-cycle',
        method: 'POST',
        statusApiVersion: 'rdap_lock37.v1',
        tableName: 'dashboard_locks',
        localOnly: true,
        confirmWriteRequired: true,
        bodyConfirmOnly: true,
        testOnlyRequired: true,
        lockTestCycleEnabled: true,
        productiveWritesEnabled: false,
        writesStillBlockedForProductiveActions: true,
        adminNoteWritesEnabled: false,
        auditProductiveWritesEnabled: false,
        uiWriteButtonsEnabled: false,
        secretsLogged: false,
        physicalDeleteEnabled: false,
        routeRemainsRestricted: true
      },
      adminUsersMiniWriteFoundation: {
        prepared: true,
        route: '/api/remote/admin/users/mini-write-foundation-diagnostic',
        permissionPrepared: true,
        confirmWritePrepared: true,
        auditPrepared: true,
        lockPrepared: true,
        backupRollbackPrepared: true,
        writeEnabled: false,
        productiveWritesEnabled: false,
        writesStillBlocked: true,
        uiWriteButtonsEnabled: false,
        routeRemainsReadOnly: true
      },
      localLanMode: {
        planned: true,
        implemented: false,
        twitchLoginPlanned: true,
        todoParkedUntilWebDashboardStable: true
      },
      safety: context.safety
    });
  });
}

module.exports = { registerRoutesRoutes };
